/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.github.williamcosta303.visao;

import javax.swing.JOptionPane;
import com.github.williamcosta303.controle.ControleBanco;
import com.github.williamcosta303.modelo.Login;
import java.sql.SQLException;

/**
 *
 * @author William
 */
public class AlterarSenha extends javax.swing.JInternalFrame {
    
    //private String username;
    private int codigoUsuario;
    private String nomeUsuario;
    
    /**
     * Creates new form AlterarSenha
     */
    public AlterarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cSenhaAtual = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cNovaSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cConfirmaNovaSenha = new javax.swing.JPasswordField();
        bAlterarSenha = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alterar senha");

        jLabel1.setText("Logado como: -");

        jLabel2.setText("Senha atual:");

        jLabel3.setText("Nova senha:");

        jLabel4.setText("Confirmar senha:");

        bAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/williamcosta303/imagens/trocaSenha-16.png"))); // NOI18N
        bAlterarSenha.setText("Alterar senha");
        bAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cConfirmaNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(bAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cConfirmaNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bAlterarSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarSenhaActionPerformed
        try{
            ControleBanco CB = new ControleBanco();
            if(isSenhaOriginalCorreta() && isNovaSenhaValida() && isSenhasDigitadasIguais()){
                Login L = new Login();
                L.setCodigo(this.codigoUsuario);
                L.setSenha(this.getNovaSenha());
                
                CB.atualizarCadastro(L, true);
                
                JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!\nEssa janela será fechada!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                String msgErros = "Os seguintes erros devem ser verificados:";
                if(!isNovaSenhaValida()){
                    msgErros += "\n* A nova senha não é válida!";
                }
                if(!isSenhasDigitadasIguais()){
                    msgErros += "\n* As senhas digitadas não são iguais!";
                }
                JOptionPane.showMessageDialog(this, msgErros, "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }catch(SQLException SE){
            JOptionPane.showMessageDialog(this, SE.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }catch(Exception E){
            JOptionPane.showMessageDialog(this, "Senha original incorreta!\nVerifique e tente novamente!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAlterarSenhaActionPerformed

    
    public void receberDados(int codigoUsuario, String nomeUsuario){
        this.codigoUsuario = codigoUsuario;
        this.nomeUsuario = nomeUsuario;
        this.jLabel1.setText("Logado como: " + nomeUsuario);
    }
    
    private boolean isSenhasDigitadasIguais(){
        // Verifica se as senhas digitadas estão corretas
        String tmpSenha1 = "", tmpSenha2 = "";
        for(int i = 0; i < this.cNovaSenha.getPassword().length; i++){
            tmpSenha1+= this.cNovaSenha.getPassword()[i];
        }
        for(int i = 0; i < this.cConfirmaNovaSenha.getPassword().length; i++){
            tmpSenha2+= this.cConfirmaNovaSenha.getPassword()[i];
        }
        
        return tmpSenha1.equals(tmpSenha2);
    }
    
    private boolean isNovaSenhaValida(){
        String tmpSenha = "";
        for(int i = 0; i < this.cNovaSenha.getPassword().length; i++){
            tmpSenha+= this.cNovaSenha.getPassword()[i];
        }
        return tmpSenha.length() > 0 && tmpSenha.length() <= 30;
    }
    
    private boolean isSenhaOriginalCorreta() throws SQLException, Exception{
        ControleBanco CB = new ControleBanco();
        String tmpSenha = "";
        for(int i = 0; i < this.cSenhaAtual.getPassword().length; i++){
            tmpSenha+= this.cSenhaAtual.getPassword()[i];
        }
        
        return CB.verificarLogin(this.nomeUsuario, tmpSenha);
    }
    
    private String getNovaSenha(){
        String senha = "";
        for(int i = 0; i < this.cNovaSenha.getPassword().length; i++){
            senha+=this.cNovaSenha.getPassword()[i];
        }
        return senha;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterarSenha;
    private javax.swing.JPasswordField cConfirmaNovaSenha;
    private javax.swing.JPasswordField cNovaSenha;
    private javax.swing.JPasswordField cSenhaAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
