package com.github.williamcosta303.visao;

import java.awt.*;
import javax.swing.JOptionPane;

public class Index extends javax.swing.JFrame {

    String username;
    int privilegio, codigoEquipe, codigoUsuario;
    
    // WASTE OF TIME
    int quantidade = 0;
    
    // Janelas
    Chamados MC = new Chamados();
    AbrirChamado AC = new AbrirChamado();
    AdministrarUsuarios AdmUs = new AdministrarUsuarios();
    AlterarSenha AS = new AlterarSenha();
    
    public Index(int codigoUsuario, String username, int privilegio, int codigoEquipe) {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.username = username;
        this.privilegio = privilegio;
        this.codigoEquipe = codigoEquipe;
        this.codigoUsuario = codigoUsuario;
        
        AC.atualizarNomeLogado(this.username);
        MC.atualizarCampos(this.username, this.codigoUsuario, this.codigoEquipe);
        AdmUs.privilegio = this.privilegio;
        AS.receberDados(this.codigoUsuario, this.username);
        
        this.lBemVindo.setText("Bem-vindo ao sistema, " + this.username + "!");
        
        if(this.codigoEquipe == 1){
            this.setaPermissoes(true);
        } else {
            this.jDesktopPane1.add(MC);
            MC.atualizarTabelaUsuario();
            MC.atualizarTabelaEquipe();
            MC.atualizarTabelaChamados(0, false, this.codigoEquipe ,0);
            MC.receberEquipes();
            MC.setVisible(true);
            //MC.atualizarUsername(this.username);
            this.setaPermissoes(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lBemVindo = new javax.swing.JLabel();
        bLogoff = new javax.swing.JButton();
        painelPermissoesAdm = new javax.swing.JPanel();
        bAdministracao = new javax.swing.JButton();
        bAbrirChamado = new javax.swing.JButton();
        bAlterarSenha = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chamados de TI");
        setIconImage(Toolkit.getDefaultToolkit().getImage(Index.class.getResource("icone.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lTitulo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/williamcosta303/imagens/logotipo.png"))); // NOI18N
        lTitulo.setText("Chamados de TI");
        lTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTituloMouseClicked(evt);
            }
        });

        lBemVindo.setText("Bem-vindo ao sistema, [usuario]!");

        bLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/williamcosta303/imagens/logoff-8.png"))); // NOI18N
        bLogoff.setText("Logoff");
        bLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoffActionPerformed(evt);
            }
        });

        bAdministracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/williamcosta303/imagens/admin-16.png"))); // NOI18N
        bAdministracao.setText("Administração");
        bAdministracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdministracaoActionPerformed(evt);
            }
        });

        bAbrirChamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/williamcosta303/imagens/novoCh-16.png"))); // NOI18N
        bAbrirChamado.setText("Abrir chamado");
        bAbrirChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirChamadoActionPerformed(evt);
            }
        });

        bAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/williamcosta303/imagens/senha-16.png"))); // NOI18N
        bAlterarSenha.setText("Alterar senha");
        bAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPermissoesAdmLayout = new javax.swing.GroupLayout(painelPermissoesAdm);
        painelPermissoesAdm.setLayout(painelPermissoesAdmLayout);
        painelPermissoesAdmLayout.setHorizontalGroup(
            painelPermissoesAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPermissoesAdmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAbrirChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAlterarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAdministracao)
                .addContainerGap())
        );
        painelPermissoesAdmLayout.setVerticalGroup(
            painelPermissoesAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPermissoesAdmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPermissoesAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAbrirChamado)
                    .addComponent(bAdministracao)
                    .addComponent(bAlterarSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLogoff))
                    .addComponent(painelPermissoesAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBemVindo)
                    .addComponent(bLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPermissoesAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTituloMouseClicked
        if(this.quantidade < 10){
            this.quantidade++;
        } else if (this.quantidade == 10) {
            JOptionPane.showMessageDialog(this, "Não importa o quanto você clique, não tem nada aqui...", "Programa desenvolvido por: William A. Costa", JOptionPane.WARNING_MESSAGE);
            this.quantidade++;
        }
    }//GEN-LAST:event_lTituloMouseClicked

    private void bLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoffActionPerformed
        this.realizarLogoff();
    }//GEN-LAST:event_bLogoffActionPerformed

    private void bAdministracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdministracaoActionPerformed
        if(this.privilegio == 2){
            if(!AdmUs.isVisible()){
                this.jDesktopPane1.add(AdmUs);
                AdmUs.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Você não tem permissões suficientes para administrar usuários!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAdministracaoActionPerformed

    private void bAbrirChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirChamadoActionPerformed
        if(!AC.isVisible()){
            this.jDesktopPane1.add(AC);
            AC.setVisible(true);
        }
    }//GEN-LAST:event_bAbrirChamadoActionPerformed

    private void bAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarSenhaActionPerformed
        if(!AS.isVisible()){
            this.jDesktopPane1.add(AS);
            AS.setVisible(true);
        }
    }//GEN-LAST:event_bAlterarSenhaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.realizarLogoff();
    }//GEN-LAST:event_formWindowClosing

    private void setaPermissoes(boolean isUsuario){
        this.bAdministracao.setEnabled(!isUsuario);
    }
    
    private void realizarLogoff(){
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja fazer logoff?", "Logoff", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Realizando logoff!", "Logoff", JOptionPane.INFORMATION_MESSAGE);
            TelaLogin TL = new TelaLogin();
            TL.setVisible(true);

            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrirChamado;
    private javax.swing.JButton bAdministracao;
    private javax.swing.JButton bAlterarSenha;
    private javax.swing.JButton bLogoff;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lBemVindo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel painelPermissoesAdm;
    // End of variables declaration//GEN-END:variables
}
